// AUTO-GENERATED by site/scripts/gen-types.mjs from ../schema/*.json.
// DO NOT EDIT by hand — regenerate via `npm run gen-types` or `npm run build`.
// Source of truth: pipeline/models.py (Pydantic).

export type ControlParadigm = 'prevention' | 'detection' | 'correction' | 'recovery';
export type TemporalPhase = 'pre_generation' | 'in_generation' | 'post_generation';
export type AutonomyLevel = 'fully_autonomous' | 'graduated_hitl' | 'full_hitl';
export type LocusOfControl = 'model' | 'prompt' | 'context' | 'environment' | 'human';
export type MaturityStatus = 'experimental' | 'stable' | 'at_risk' | 'deprecated' | 'abandoned';
export type FailureModeId =
  | 'fabrication'
  | 'obsolescence'
  | 'dependency_blindness'
  | 'logic_error'
  | 'security_vulnerability'
  | 'scope_creep'
  | 'context_pollution'
  | 'supply_chain_attack';
export type CrosswalkConfidence = 'exact' | 'partial' | 'broader' | 'narrower' | 'related';
export type SaicaAxis =
  | 'failure_mode'
  | 'control_paradigm'
  | 'temporal_phase'
  | 'autonomy_level'
  | 'locus_of_control';

export interface CrosswalkEntry {
  taxonomy: string;
  external_id: string;
  confidence: CrosswalkConfidence;
  note?: string;
}

export interface TaxonomyCategory {
  external_id: string;
  label: string;
  description?: string;
  parent_id?: string;
}

export interface CrosswalkMapping {
  saica_value: string;
  external_id: string;
  confidence: CrosswalkConfidence;
  note?: string;
}

/**
 * A software artifact that supervises AI coding agents.
 */
export interface Tool {
  /**
   * Stable kebab-case slug. Never changes.
   */
  id: string;
  name: string;
  tagline?: string;
  description: string;
  first_released: string;
  last_updated?: string;
  maturity_status: MaturityStatus;
  /**
   * Organization node id.
   */
  published_by?: string;
  repository_url?: string;
  documentation_url?: string;
  /**
   * SPDX identifier or 'proprietary'.
   */
  license: string;
  control_paradigm: ControlParadigm;
  temporal_phase: TemporalPhase;
  autonomy_level: AutonomyLevel;
  /**
   * @minItems 1
   */
  addresses_failure_modes: (
      | 'fabrication'
      | 'obsolescence'
      | 'dependency_blindness'
      | 'logic_error'
      | 'security_vulnerability'
      | 'scope_creep'
      | 'context_pollution'
      | 'supply_chain_attack'
      | 'cascading_failure'
      | 'incomplete_execution'
      | 'test_manipulation'
    )[];
  locus_of_control?: LocusOfControl[];
  /**
   * How this tool is deployed / consumed. Multi-valued — a tool can ship as several surfaces (e.g. cli + ci_app + library).
   */
  integration_surfaces?: (
    | 'ide_plugin'
    | 'desktop_app'
    | 'web_app'
    | 'cli'
    | 'library'
    | 'http_service'
    | 'mcp_server'
    | 'ci_app'
    | 'proxy_gateway'
  )[];
  implements_techniques?: string[];
  /**
   * Symmetric; both sides must declare.
   */
  composes_with?: string[];
  /**
   * Directed composition. A feeds_into B means A's output is consumed by B.
   */
  feeds_into?: string[];
  supersedes?: string[];
  /**
   * Libraries/runtimes the tool itself imports.
   */
  runtime_requires?: string[];
  /**
   * Library / language / ecosystem the tool watches over.
   */
  supervises_targets?: string[];
  cited_in?: string[];
  documented_in?: string[];
  evaluated_on?: string[];
  security_notes?: string;
  signed_manifest?: boolean;
  openssf_scorecard_score?: number | null;
  /**
   * GitHub stargazer count, refreshed periodically by validator/fetch_github_stars.py.
   */
  stars?: number;
  /**
   * Date the stars count was last fetched (YYYY-MM-DD).
   */
  stars_updated_at?: string;
  contributors?: string[];
  editorial_notes?: string;
  inclusion_rationale?: string;
  /**
   * How this tool entered the KG. Optional on pre-existing nodes; newly-graduated tools must populate this.
   */
  provenance?: {
    /**
     * Where this node came from (e.g. 'manual', 'pipeline-v0.1', 'import-from-awesome-list').
     */
    source: string;
    /**
     * Date the node entered data/ (YYYY-MM-DD).
     */
    ingested_at: string;
    /**
     * LLM identifier that produced the structured draft (e.g. 'Kimi-K2.5').
     */
    extractor_model?: string;
    /**
     * Overall LLM confidence attached to the extraction payload (0-1).
     */
    extractor_confidence?: number;
    /**
     * Cohere rerank score used to prioritize this candidate (0-1).
     */
    rerank_score?: number;
    /**
     * Link back to candidate_tools.id (or equivalent) in Postgres.
     */
    candidate_id?: number;
    /**
     * GitHub handle of the person who merged the node.
     */
    reviewer?: string;
    /**
     * Date the merge was accepted.
     */
    review_date?: string;
  };
}

/**
 * A supervision-addressable failure class.
 */
export interface FailureMode {
  id: string;
  name: string;
  tagline?: string;
  description: string;
  /**
   * Alternative names used in the field.
   */
  aliases?: string[];
  /**
   * Other FailureMode ids to disambiguate from.
   */
  related_modes?: string[];
  /**
   * Paper ids grounding this class in the literature.
   *
   * @minItems 1
   */
  prior_work: string[];
  /**
   * How to recognize an instance.
   *
   * @minItems 1
   */
  detection_signals: string[];
  /**
   * Paper id that formalizes this definition, if any.
   */
  canonical_definition_source?: string;
  /**
   * Explicit mappings from this SAICA-KG class into external taxonomies.
   */
  crosswalks?: {
    /**
     * Taxonomy node id.
     */
    taxonomy: string;
    /**
     * Category id or label within that taxonomy.
     */
    external_id: string;
    confidence: CrosswalkConfidence;
    note?: string;
  }[];
}

/**
 * An academic or gray-literature reference used to ground nodes in SAICA-KG.
 */
export interface Paper {
  id: string;
  /**
   * @minItems 1
   */
  authors: string[];
  year: number;
  title: string;
  venue?: string;
  url?: string;
  doi?: string;
  arxiv_id?: string;
  semantic_scholar_id?: string;
  abstract?: string;
  tldr?: string;
  citation_count?: number;
  /**
   * Free tags to help editorial grouping (e.g. 'failure-mode-taxonomy', 'MCP-benchmark').
   */
  relevance_tags?: string[];
  notes?: string;
}

/**
 * An external failure-mode or risk taxonomy that SAICA-KG cross-walks into its own facets.
 */
export interface Taxonomy {
  id: string;
  name: string;
  /**
   * Owning organization or working group.
   */
  owner: string;
  /**
   * Version or year identifier of the external taxonomy as of ingestion.
   */
  version: string;
  first_published?: string;
  last_updated?: string;
  url?: string;
  license?: string;
  /**
   * Paper node id if the taxonomy is published academically.
   */
  paper_id?: string;
  /**
   * What the taxonomy covers (e.g., 'failure modes for multi-agent systems').
   */
  scope?: string;
  /**
   * @minItems 1
   */
  categories: {
      /**
       * The taxonomy's own identifier for this category (e.g., 'ASI04', 'MAS-FM-7').
       */
      external_id: string;
      label: string;
      description?: string;
      /**
       * If the taxonomy is hierarchical.
       */
      parent_id?: string;
    }[];
  notes?: string;
  inclusion_rationale?: string;
}

/**
 * A bulk mapping between a SAICA-KG axis and an external taxonomy's categories. Complements inline `crosswalks` declared on FailureMode nodes.
 */
export interface Crosswalk {
  id: string;
  saica_axis: SaicaAxis;
  /**
   * Taxonomy node id.
   */
  taxonomy: string;
  authored_by?: string[];
  reviewed_by?: string[];
  last_reviewed?: string;
  /**
   * @minItems 1
   */
  mappings: {
      /**
       * Value on the SAICA axis (e.g., a FailureMode id).
       */
      saica_value: string;
      /**
       * Category id in the external taxonomy.
       */
      external_id: string;
      confidence: CrosswalkConfidence;
      note?: string;
    }[];
}

/**
 * A documented failure event where an AI coding agent (or analogous system) produced harm. Anchors FailureMode claims in ground truth.
 */
export interface Incident {
  id: string;
  title: string;
  tagline?: string;
  description: string;
  incident_date: string;
  harm_class: 'user_reported' | 'data_loss' | 'security_breach' | 'financial_loss' | 'reputational';
  reproducibility: 'confirmed' | 'plausible' | 'anecdotal';
  /**
   * @minItems 1
   */
  exhibited_failure_modes: (
      | 'fabrication'
      | 'obsolescence'
      | 'dependency_blindness'
      | 'logic_error'
      | 'security_vulnerability'
      | 'scope_creep'
      | 'context_pollution'
      | 'supply_chain_attack'
      | 'cascading_failure'
      | 'incomplete_execution'
      | 'test_manipulation'
    )[];
  /**
   * Free-form tool / product / system names involved.
   */
  affected_systems?: string[];
  /**
   * Publicly resolvable citations describing the incident.
   *
   * @minItems 1
   */
  source_urls: string[];
  /**
   * Paper node ids that discuss or analyze this incident.
   */
  documented_by?: string[];
  /**
   * Tool node ids whose supervision would plausibly prevent the incident.
   */
  mitigated_by?: string[];
  notes?: string;
}

/**
 * An ordered composition of Tools that addresses one or more FailureModes. Recipes are the prescriptive flip-side of Incidents.
 */
export interface Recipe {
  id: string;
  name: string;
  tagline?: string;
  description: string;
  /**
   * @minItems 1
   */
  targets_failure_modes: (
      | 'fabrication'
      | 'obsolescence'
      | 'dependency_blindness'
      | 'logic_error'
      | 'security_vulnerability'
      | 'scope_creep'
      | 'context_pollution'
      | 'supply_chain_attack'
      | 'cascading_failure'
      | 'incomplete_execution'
      | 'test_manipulation'
    )[];
  /**
   * Ordered list of Tool ids that compose the recipe.
   *
   * @minItems 2
   */
  stack: [string, string, ...string[]];
  evidence_tier: 'anecdotal' | 'case_studied' | 'benchmark_validated';
  /**
   * Primary language / stack (e.g. python, typescript, polyglot).
   */
  language?: string;
  notes?: string;
}

export interface Graph {
  tools: Record<string, Tool>;
  failureModes: Record<string, FailureMode>;
  taxonomies: Record<string, Taxonomy>;
  papers: Record<string, Paper>;
  crosswalks: Record<string, Crosswalk>;
  incidents: Record<string, Incident>;
  recipes: Record<string, Recipe>;
  // Derived indexes:
  toolsByFailureMode: Record<string, string[]>;
  failureModesByTaxonomyCategory: Record<string, Record<string, string[]>>;
  kgVersion: string;
  kgLastUpdated: string; // ISO
}
