"""Markdown renderer for AuditReport.

Produces a single self-contained Markdown document the user can paste
into team docs.  Sections (in order):

  # Audit: <repo>
  **Audited:** YYYY-MM-DD

  ## Executive summary
  ## Detected stack          (compact table)
  ## Coverage                 (FM × paradigm tier table)
  ## Gaps and recommendations (one subsection per gap)
  ## Unresolved detections    (only if any)

  ---
  Generated by SAICA-KG v0.2 — saica-kg.dev
"""

from __future__ import annotations

from typing import Iterable

from pipeline.audit.coverage import PARADIGMS
from pipeline.audit.kg import FM_DISPLAY, load_failure_modes
from pipeline.audit.schemas import (
    AuditReport,
    CoverageGrid,
    DetectedStack,
    GapItem,
    Recommendation,
)


def _repo_label(repo_url: str) -> str:
    return repo_url.rstrip("/").rsplit("/", 1)[-1] or repo_url


def _join_or_dash(items: Iterable[str]) -> str:
    items = [i for i in items if i]
    return ", ".join(items) if items else "—"


def _render_stack_table(stack: DetectedStack) -> str:
    agents = _join_or_dash(f"{a.name} ({a.id})" for a in stack.agents)
    sup = _join_or_dash(f"{t.name}" for t in stack.supervision_tools if t.in_kg)
    rows = [
        ("Languages", _join_or_dash(stack.languages)),
        ("Runtime hints", _join_or_dash(stack.runtime_hints)),
        ("Package managers", _join_or_dash(stack.package_managers)),
        ("CI providers", _join_or_dash(stack.ci_providers)),
        ("Coding agents", agents),
        ("Supervision tools", sup),
    ]
    out = ["| Signal | Value |", "| --- | --- |"]
    for k, v in rows:
        out.append(f"| {k} | {v} |")
    return "\n".join(out)


def _render_coverage_table(coverage: CoverageGrid) -> str:
    fm_ids = load_failure_modes()
    by_fm: dict[str, dict[str, int]] = {}
    for cell in coverage.cells:
        by_fm.setdefault(cell.failure_mode, {})[cell.paradigm] = cell.tier

    headers = ["Failure mode"] + [p.title() for p in PARADIGMS]
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(["---"] * len(headers)) + " |",
    ]
    for fm in fm_ids:
        row = [FM_DISPLAY.get(fm, fm.replace("_", " ").title())]
        for paradigm in PARADIGMS:
            tier = by_fm.get(fm, {}).get(paradigm, 0)
            row.append(str(tier) if tier > 0 else "·")
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def _render_recommendation(rec: Recommendation) -> str:
    surfaces = ", ".join(rec.integration_surfaces) or "—"
    star_str = f" · {rec.stars}★" if rec.stars else ""
    return (
        f"  - **[{rec.tool_name}]({rec.url})** "
        f"({rec.paradigm} · {rec.temporal_phase}{star_str}) — {rec.why} "
        f"_Surfaces: {surfaces}._"
    )


def _render_gap(gap: GapItem) -> str:
    pretty_fm = FM_DISPLAY.get(
        gap.failure_mode, gap.failure_mode.replace("_", " ").title()
    )
    sev_label = gap.severity.upper()
    parts = [f"### {pretty_fm} — {sev_label}", gap.rationale]
    if gap.recommendations:
        parts.append("")
        parts.append("Suggested tools:")
        parts.extend(_render_recommendation(r) for r in gap.recommendations)
    else:
        parts.append("")
        parts.append("_No KG candidate found — consider opening a PR to add one._")
    return "\n".join(parts)


def _render_unresolved(stack: DetectedStack) -> str:
    if not stack.unresolved_tools:
        return ""
    lines = [
        "## Unresolved detections",
        "",
        "We detected these tools but they aren't yet in the SAICA-KG. "
        "Consider opening a PR to add them so they show up in coverage and "
        "recommendations.",
        "",
    ]
    for t in stack.unresolved_tools:
        paths = ", ".join(t.detection_paths) or "—"
        lines.append(f"- **{t.name}** (source: {t.detection_source}; paths: {paths})")
    return "\n".join(lines)


def to_markdown(report: AuditReport) -> str:
    """Render a complete AuditReport as Markdown."""
    repo = _repo_label(report.repo_url)
    lines: list[str] = []

    lines.append(f"# Audit: [{repo}]({report.repo_url})")
    lines.append("")
    lines.append(f"**Audited:** {report.audited_at.isoformat()}")
    lines.append("")
    lines.append("## Executive summary")
    lines.append("")
    lines.append(report.summary.strip())
    lines.append("")
    lines.append("## Detected stack")
    lines.append("")
    lines.append(_render_stack_table(report.stack))
    lines.append("")
    lines.append("## Coverage")
    lines.append("")
    lines.append(
        "Cells show the highest evidence tier among your detected tools "
        "for each (failure-mode × paradigm) pair. `1` = declared mapping, "
        "`2` = + rationale discusses the FM, `3` = + external citation, "
        "`·` = uncovered."
    )
    lines.append("")
    lines.append(_render_coverage_table(report.coverage))
    lines.append("")
    lines.append(
        "_Paradigm balance:_ "
        + ", ".join(f"{p}={n}" for p, n in report.coverage.paradigm_balance.items())
    )
    lines.append("")
    lines.append("## Gaps and recommendations")
    lines.append("")
    if report.gaps:
        for gap in report.gaps:
            lines.append(_render_gap(gap))
            lines.append("")
    else:
        lines.append(
            "_No gaps detected — your stack covers every failure mode "
            "with at least two paradigms._"
        )
        lines.append("")

    unresolved = _render_unresolved(report.stack)
    if unresolved:
        lines.append(unresolved)
        lines.append("")

    lines.append("---")
    lines.append("Generated by SAICA-KG v0.2 — saica-kg.dev")

    return "\n".join(lines).rstrip() + "\n"


__all__ = ["to_markdown"]
